### ISSUE TITLE
Meet InterCEPT RFP Specs

### ISSUE THREAD

**Issue by wraybowling** [RCPL/v3#129]
INITIATIVE 1: CUSTOMER ENGAGMENT TOOL (INTERCEPT) 
InterCEPT will have the following Objectives

Develop an open source application (or multiple applications) that includes:
- a customer participation/engagement tracking component 
- a calendaring system
- a room/equipment reservation component
- the ability to seamlessly connect with a library’s ILS (Integrated Library System), the 
software that manages a customer’s library account.

Pilot the new (InterCEPT) tool at Richland Library and other partner library systems. InterCEPT
will have the following outcomes:

To improve library event programming so that it meets the needs of the community.

To better understand the outcome, reach and efficacy of library learning opportunities on attendees. InterCEPT will have the following Scope of Services:

Functionality for Customers & Staff:
- [x] Method to track individual customer attendance and tie it back to the ILS #125, #126
- [x] Room & equipment reservation #127, #11, #109, #115, #5,
- [x] Calendar views #130, #116, #28 
- [x] Event searching #96, #133

Staff functionality:
- [x] The ability to be integrated with the most popular integrated library systems (ILS) amongst public libraries #132
- [x] Customer program attendance, retrievable and exportable, displayed alongside customer information #125 
- [x] Ability to create an event posting that includes information for related catalog items #25

Developer functionality:
- [x] Code should be made available in an open source format that will allow free download, usage, and modifications by other unaffiliated libraries #131 
- [x] Ability to connect with the data source through an API or other method that allows pushing and pulling of all major data points #132

**Comment by wraybowling** [comment]
Converted to milestone https://github.com/RCPL/v3/milestone/4
